### ISSUE TITLE
variation in values in Email report and O365 admin center extracted report

### ISSUE THREAD

**Issue by fidagithub** [junecastillote/Ms365UsageReport#10]
There is some variation in values that we got on the email reporting as attached in the given excel sheet.
Eg:- We should be getting 0 for "Inactive mailbox" since we don't have an org-wide hold or retention policy applied.Eventhough it shows different value for inactive mailbox count.

[MBR Research.xlsx](https://github.com/junecastillote/Ms365UsageReport/files/6967890/MBR.Research.xlsx)

**Comment by junecastillote** [comment]
An inactive mailbox means a mailbox without any activity within the specified period in this report.
